services:
  - type: web
    name: fastapi-university-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: LLM_MODEL
        sync: false
